# Generated by Django 4.2.14 on 2024-08-02 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leamington_blog_app', '0002_post_number_of_comments_post_number_of_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leamington_blog_app.post'),
        ),
    ]
