# Generated by Django 4.2.14 on 2024-08-04 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leamington_blog_app', '0004_profile_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
