# Generated by Django 4.2.14 on 2024-08-04 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leamington_blog_app', '0005_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='number_of_likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
