# Generated by Django 4.2.14 on 2024-08-06 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leamington_blog_app', '0008_alter_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='admin_editable',
        ),
    ]
